
package com.safeval.codeanalyzer.ws.login;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "LoginServiceSoap", targetNamespace = "http://ws.isasecdev.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface LoginServiceSoap {


    /**
     * 
     * @param password
     * @param fvers
     * @param vers
     * @param login
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "Login", action = "http://ws.isasecdev.com/Login")
    @WebResult(name = "LoginResult", targetNamespace = "http://ws.isasecdev.com/")
    @RequestWrapper(localName = "Login", targetNamespace = "http://ws.isasecdev.com/", className = "com.safeval.Login")
    @ResponseWrapper(localName = "LoginResponse", targetNamespace = "http://ws.isasecdev.com/", className = "com.safeval.LoginResponse")
    public String login(
        @WebParam(name = "login", targetNamespace = "http://ws.isasecdev.com/")
        String login,
        @WebParam(name = "password", targetNamespace = "http://ws.isasecdev.com/")
        String password,
        @WebParam(name = "vers", targetNamespace = "http://ws.isasecdev.com/")
        String vers,
        @WebParam(name = "fvers", targetNamespace = "http://ws.isasecdev.com/")
        long fvers);

}
