
package com.safeval.codeanalyzer.ws.login;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "LoginService", targetNamespace = "http://safeval.com/", wsdlLocation = "http://localhost/safeval/Login/LoginService.asmx?wsdl")
public class LoginService
    extends Service
{

    private final static URL LOGINSERVICE_WSDL_LOCATION;
    private final static WebServiceException LOGINSERVICE_EXCEPTION;
    private final static QName LOGINSERVICE_QNAME = new QName("http://safeval.com/", "LoginService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost/safeval/Login/LoginService.asmx?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        LOGINSERVICE_WSDL_LOCATION = url;
        LOGINSERVICE_EXCEPTION = e;
    }

    public LoginService() {
        super(__getWsdlLocation(), LOGINSERVICE_QNAME);
    }

    public LoginService(WebServiceFeature... features) {
        super(__getWsdlLocation(), LOGINSERVICE_QNAME, features);
    }

    public LoginService(URL wsdlLocation) {
        super(wsdlLocation, LOGINSERVICE_QNAME);
    }

    public LoginService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, LOGINSERVICE_QNAME, features);
    }

    public LoginService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public LoginService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns LoginServiceSoap
     */
    @WebEndpoint(name = "LoginServiceSoap")
    public LoginServiceSoap getLoginServiceSoap() {
        return super.getPort(new QName("http://safeval.com/", "LoginServiceSoap"), LoginServiceSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns LoginServiceSoap
     */
    @WebEndpoint(name = "LoginServiceSoap")
    public LoginServiceSoap getLoginServiceSoap(WebServiceFeature... features) {
        return super.getPort(new QName("http://safeval.com/", "LoginServiceSoap"), LoginServiceSoap.class, features);
    }

    private static URL __getWsdlLocation() {
        if (LOGINSERVICE_EXCEPTION!= null) {
            throw LOGINSERVICE_EXCEPTION;
        }
        return LOGINSERVICE_WSDL_LOCATION;
    }

}
