
package com.safeval.codeanalyzer.ws.analysis;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "AnalysisService", targetNamespace = "http://ws.isasecdev.com/", wsdlLocation = "https://isasecdev.com/Analysis/AnalysisService.asmx?wsdl")
public class AnalysisService
    extends Service
{

    private final static URL ANALYSISSERVICE_WSDL_LOCATION;
    private final static WebServiceException ANALYSISSERVICE_EXCEPTION;
    private final static QName ANALYSISSERVICE_QNAME = new QName("http://ws.isasecdev.com/", "AnalysisService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("https://isasecdev.com/Analysis/AnalysisService.asmx?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        ANALYSISSERVICE_WSDL_LOCATION = url;
        ANALYSISSERVICE_EXCEPTION = e;
    }

    public AnalysisService() {
        super(__getWsdlLocation(), ANALYSISSERVICE_QNAME);
    }

    public AnalysisService(WebServiceFeature... features) {
        super(__getWsdlLocation(), ANALYSISSERVICE_QNAME, features);
    }

    public AnalysisService(URL wsdlLocation) {
        super(wsdlLocation, ANALYSISSERVICE_QNAME);
    }

    public AnalysisService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, ANALYSISSERVICE_QNAME, features);
    }

    public AnalysisService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public AnalysisService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns AnalysisServiceSoap
     */
    @WebEndpoint(name = "AnalysisServiceSoap")
    public AnalysisServiceSoap getAnalysisServiceSoap() {
        return super.getPort(new QName("http://ws.isasecdev.com/", "AnalysisServiceSoap"), AnalysisServiceSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns AnalysisServiceSoap
     */
    @WebEndpoint(name = "AnalysisServiceSoap")
    public AnalysisServiceSoap getAnalysisServiceSoap(WebServiceFeature... features) {
        return super.getPort(new QName("http://ws.isasecdev.com/", "AnalysisServiceSoap"), AnalysisServiceSoap.class, features);
    }

    private static URL __getWsdlLocation() {
        if (ANALYSISSERVICE_EXCEPTION!= null) {
            throw ANALYSISSERVICE_EXCEPTION;
        }
        return ANALYSISSERVICE_WSDL_LOCATION;
    }

}
